//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuskStopInfo
    {
        public int ID { get; set; }
        public int GG { get; set; }
        public string TypeData { get; set; }
        public System.DateTime TimeOn { get; set; }
        public System.DateTime TimeOff { get; set; }
        public double Length { get; set; }
        public double ValueStart { get; set; }
        public double ValueEnd { get; set; }
        public string Comment { get; set; }
    }
}
