//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuskStopPoint
    {
        public int ID { get; set; }
        public int gg { get; set; }
        public string pointType { get; set; }
        public string point { get; set; }
        public bool inverted { get; set; }
        public bool analog { get; set; }
    }
}
